app-template:
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/gethomepage/homepage
            tag: v1.13.2
          env:
            HOMEPAGE_ALLOWED_HOSTS: home.daxvo.tech
  service:
    main:
      ports:
        http:
          port: 3000
          protocol: HTTP
  route:
    main:
      enabled: true
      hostnames:
        - home.daxvo.tech
      parentRefs:
        - name: public-gateway
          namespace: gateway-system
          sectionName: http
        - name: public-gateway
          namespace: gateway-system
          sectionName: https
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: homepage
              port: 3000
  persistence:
    config:
      enabled: true
      type: configMap
      identifier: config
      globalMounts:
        - path: /app/config/settings.yaml
          subPath: settings.yaml
        - path: /app/config/widgets.yaml
          subPath: widgets.yaml
        - path: /app/config/services.yaml
          subPath: services.yaml
        - path: /app/config/bookmarks.yaml
          subPath: bookmarks.yaml
  configMaps:
    config:
      enabled: true
      data:
        settings.yaml: |
          title: Homelabing
          background: https://darksky.org/app/uploads/2023/07/Griselda-Hill-under-Milky-Way-Morgan-Sette-scaled-1.jpg
          cardBlur: sx
          theme: light
          headerStyle: boxed
          hideVersion: true
          color: yellow
        widgets.yaml: |
          - search:
              provider: google
              target: _blank
        services.yaml: |
          - Development:
            - ArgoCD:
                href: https://argocd.daxvo.tech
                description: Continuous deployment
                icon: https://icon.icepanel.io/Technology/svg/Argo-CD.svg
        bookmarks.yaml: |
          - Homelab:
            - Repository:
              - href: https://github.com/chpiano2000/Homelabing
                icon: github.svg
          - Managed services:
            - Cloudflare:
              - href: https://dash.cloudflare.com
                icon: cloudflare.svg
          - Infrastructure:
            - Proxmox:
              - href: https://10.0.0.50:8006
                icon: proxmox.svg
            - Oracle Cloud:
              - href: https://cloud.oracle.com
                icon: oracle-cloud.svg

