# Create a directory to download RKE2 binary to
- name: Debug rke2_install_dir
  ansible.builtin.debug:
    msg: "rke2_install_dir is {{ rke2_binary_url }}"

- name: Create directory for RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}"
    state: directory
    mode: "0755"

# Download the RKE2 binary
- name: Download RKE2 binary
  ansible.builtin.get_url:
    url: "{{ rke2_binary_url }}"
    dest: "{{ rke2_install_dir }}/rke2"
    mode: "0755"

# Set permissions on the RKE2 binary
- name: Set executable permissions on the RKE2 binary
  ansible.builtin.file:
    path: "{{ rke2_install_dir }}/rke2"
    mode: "0755"
    state: file
