apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: {{ .Values.gateway.name }}
  ingress:
    - fromCIDR:
      {{- range .Values.networkPolicy.allowedCIDRs }}
        - {{ . | quote}}
      {{- end}}

