{{- range .Values.gateways }}
{{- if not .public }}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ .name }}-internal-only
  namespace: {{ $.Values.namespace }}
spec:
  endpointSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: {{ .name }}
  ingress:
    - fromCIDR:
      {{- range .allowedCIDRs }}
        - {{ . | quote }}
      {{- end }}
{{- end }}
{{- end }}
