- name: Set role facts
  ansible.builtin.set_fact:
    in_server: "{{ inventory_hostname == groups['servers'][0] }}"
    in_agents: "{{ inventory_hostname in groups['agents'] }}"

- name: Deploy RKE2 Agent Configuration
  ansible.builtin.template:
    src: templates/agent-config.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: "0644"
  when: in_agents

# Check agents have restarted to pick up config
- name: Ensure RKE2 agents are enabled and running
  ansible.builtin.systemd:
    name: rke2-agent
    enabled: true
    state: restarted
    daemon_reload: true
