k3s_service_file: /etc/systemd/system/k3s.service
k3s_server_config:
  tls-san:
    - "{{ control_plane_endpoint }}"
  disable:
    - local-storage
    - servicelb
    - traefik
  disable-helm-controller: true
  disable-kube-proxy: true
  disable-network-policy: true
  flannel-backend: none
  secrets-encryption: true
