---
- name: Request agents to join the cluster
  ansible.builtin.command:
    cmd: >
      talosctl apply-config 
      --insecure 
      --nodes {{ hostvars[item].ansible_host }}
      --file {{ talos_config_dir }}/worker.yaml
  loop: "{{ groups['agents'] }}"
  delegate_to: localhost
  register: join_result
  retries: 20
  delay: 10
  until: join_result.rc == 0