---
- name: Authenticate to Proxmox API and get ticket
  uri:
    url: "https://{{ pve_api_host }}:{{ pve_api_port }}/{{ pve_api_path }}/access/ticket"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ pve_api_user }}"
      password: "{{ pve_api_password }}"
    validate_certs: no
    status_code: 200
  register: proxmox_auth
  delegate_to: localhost

- name: Set authentication facts
  set_fact:
    proxmox_ticket: "{{ proxmox_auth.json.data.ticket }}"
    proxmox_csrf_token: "{{ proxmox_auth.json.data.CSRFPreventionToken }}"
