apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: default-l2-announcement
spec:
  nodeSelector:
    matchLabels: {}
  interfaces:
    - ens\d{2}
    - eth\d{2}
  externalIPs: true
  loadBalancerIPs: true
