- name: Copy kubectl to global bin
  ansible.builtin.copy:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    remote_src: true
    mode: "0755"

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.kube"
    state: directory
    mode: "0755"

- name: Copy kubeconfig
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "/home/{{ ansible_user }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user }}"
    mode: "0600"

- name: Replace 127.0.0.1 with actual server IP
  ansible.builtin.replace:
    path: "/home/{{ ansible_user }}/.kube/config"
    regexp: "127.0.0.1"
    replace: "{{ hostvars[groups['servers'][0]]['ansible_host'] }}"
