- name: Set role facts
  ansible.builtin.set_fact:
    in_server: "{{ inventory_hostname == groups['servers'][0] }}"
    in_agents: "{{ inventory_hostname in groups['agents'] }}"

- name: Create RKE2 config directory
  ansible.builtin.file:
    path: /etc/rancher/rke2
    state: directory
    mode: "0755"

- name: Create RKE2 server directory
  ansible.builtin.file:
    path: /var/lib/rancher/rke2/server
    state: directory
    mode: "0755"
