- name: Get guest info to check whether the vmid exists.
  community.proxmox.proxmox_kvm:
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host: "{{ pve_api_host }}"
    validate_certs: false
    node: "{{ pve_api_node }}"
    vmid: "{{ item }}"
  register: purge_info
  loop: [103, 104, 105]

- name: Purge the VM
  ansible.builtin.include_tasks: purge_qemu.yaml
