---
- name: Ensure temporary manifests directory exists
  ansible.builtin.file:
    path: "{{ home_dir }}/manifests"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0755'

- name: Download Gateway API CRDs
  ansible.builtin.get_url:
    url: "{{ item }}"
    dest: '{{ home_dir }}/manifests/gateway_api_{{ item.split("/")[-1].split(".")[-2] }}.yaml'
    mode: '0664'
  loop:
    - "{{ cilium_crd_link_prefix }}/{{ cilium_gatway_api_version }}/config/crd/standard/gateway.networking.k8s.io_gateways.yaml"
    - "{{ cilium_crd_link_prefix }}/{{ cilium_gatway_api_version }}/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml"
    - "{{ cilium_crd_link_prefix }}/{{ cilium_gatway_api_version }}/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml"
    - "{{ cilium_crd_link_prefix }}/{{ cilium_gatway_api_version }}/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml"

- name: Get all the Downloaded Manifests
  ansible.builtin.find:
    paths: "{{ home_dir }}/manifests"
    patterns: "*.yaml"
  register: cni_manifest_files

- name: Apply Gateway API CRDs
  kubernetes.core.k8s:
    kubeconfig: "{{ home_dir }}/.kube/config"
    src: "{{ item.path }}"
    state: present
  loop: "{{ cni_manifest_files.files }}"
  delegate_to: localhost

- name: Add Cilium Helm Repo
  kubernetes.core.helm_repository:
    kubeconfig: "{{ home_dir }}/.kube/config"
    name: cilium
    repo_url: "https://helm.cilium.io/"

- name: Install Cilium via Helm
  kubernetes.core.helm:
    kubeconfig: "{{ home_dir }}/.kube/config"
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values:
      ipam:
        mode: kubernetes
      kubeProxyReplacement: true
      l2announcements:
        enabled: true
      externalIPs:
        enabled: true
      securityContext:
        capabilities:
          ciliumAgent:
            - CHOWN
            - KILL
            - NET_ADMIN
            - NET_RAW
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
          cleanCiliumState:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RESOURCE
      cgroup:
        autoMount:
          enabled: false
        hostRoot: /sys/fs/cgroup
      k8sServiceHost: localhost
      k8sServicePort: 7445
      gatewayAPI:
        enabled: true
        enableAlpn: true
        enableAppProtocol: true
      ingressController:
        enabled: true
        loadbalancerMode: dedicated
  delegate_to: localhost

- name: Apply Cilium resources
  kubernetes.core.k8s:
    template: "{{ item }}"
  loop:
    - ciliuml2announcementpolicy.yaml
    - ciliumloadbalancerippool.yaml
