---
- name: Stop the vm
  community.proxmox.proxmox_kvm:
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host: "{{ pve_api_host }}"
    validate_certs: false
    node: "{{ pve_api_node }}"
    vmid: "{{ item }}"
    state: stopped
  loop: [103, 104, 105]

- name: Wait for VMs to fully stop
  ansible.builtin.pause:
    seconds: 30

- name: Purge the vm
  community.proxmox.proxmox_kvm:
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host: "{{ pve_api_host }}"
    validate_certs: false
    node: "{{ pve_api_node }}"
    vmid: "{{ item }}"
    state: absent
  loop: [103, 104, 105]
