apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-app-monitoring
  namespace: dev
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app
  namespaceSelector:
    matchNames:
      - dev
  endpoints:
    - port: http
      interval: 15s
