---
- name: Set VMID fact
  ansible.builtin.set_fact:
    current_vmid: '{{ (current_vm_info.json.data | selectattr("name", "equalto", inventory_hostname) | first).vmid }}'
  when: current_vm_info.json.data | length > 0

- name: Update VM MAC addresses via API
  ansible.builtin.uri:
    url: "https://{{ pve_api_host }}:{{ pve_api_port }}/{{ pve_api_path }}/nodes/{{ pve_api_node }}/qemu/{{ current_vmid }}/config"
    method: PUT
    headers:
      Cookie: "PVEAuthCookie={{ proxmox_ticket }}"
      CSRFPreventionToken: "{{ proxmox_csrf_token }}"
    body_format: form-urlencoded
    body:
      net0: "virtio={{ mac_address }},bridge=vmbr0"
    validate_certs: false
    status_code: 200
  when: current_vmid is defined
