- name: Create VMs
  community.proxmox.proxmox_kvm:
    node: "{{ pve_api_node }}"
    api_user: "{{ pve_api_user }}"
    api_password: "{{ pve_api_password }}"
    api_host: "{{ pve_api_host }}"
    storage: "{{ storage | default('local-lvm') }}"
    full: true
    clone: "{{ cp_template if 'masters' in group_names else dp_template }}"
    name: "{{ inventory_hostname }}"
    state: present
    timeout: 100

- name: Wait for another 10 seconds
  ansible.builtin.pause:
    seconds: 10
