---
- name: Provision Infrastructure
  hosts: all
  connection: local
  gather_facts: false
  serial: 1 # don't know why running in parallel costs deadlock

  tasks:
    - name: Authenticate to Promox
      ansible.builtin.include_role:
        name: homelab.promox.promox_auth

    - name: Provision VMs
      ansible.builtin.include_role:
        name: homelab.promox.provision_vms

    - name: Get VM Ids
      ansible.builtin.include_role:
        name: homelab.promox.get_vms
      run_once: true

    - name: Setup VMs
      ansible.builtin.include_role:
        name: homelab.promox.setup_mac

    - name: Start VMs
      ansible.builtin.include_role:
        name: homelab.promox.start_vms

- name: Install Talos
  hosts: all
  connection: local
  gather_facts: false
  tasks:
