---
- name: Purge
  hosts: all
  connection: local # else ansible will do ssh to the host
  gather_facts: false
  tasks:
    - name: Authenticate to Promox
      ansible.builtin.include_role:
        name: metal.promox.promox_auth

    - name: Get VM Ids
      ansible.builtin.include_role:
        name: metal.promox.get_vms

    - name: Stop VMs
      ansible.builtin.include_role:
        name: metal.promox.stop_vms

    - name: Remove VMs
      ansible.builtin.include_role:
        name: metal.promox.remove_vms
