apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-app
  namespace: dev
spec:
  ingressClassName: nginx
  rules:
    - host: web-app-1.home-k8s.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-app
                port:
                  number: 80
